# Read the documentation: https://symfony.com/doc/current/bundles/StofDoctrineExtensionsBundle/index.html
# See the official DoctrineExtensions documentation for more details: https://github.com/doctrine-extensions/DoctrineExtensions/tree/main/doc
stof_doctrine_extensions:
    default_locale: en_US
#CLEANUP config  pour les timestamp automatique du package Stof
    orm:
        default:
            timestampable: true # not needed: listeners are not enabled by default