twig:
    default_path: '%kernel.project_dir%/templates'
    file_name_pattern: ['*.twig']
    # form_themes: ['bootstrap_(_layout.html.twig)']

# Google analytics
#     globals:
#         ga_tracking: 'UA-xxxxxx-xx'
when@test:
    twig:
        strict_variables: true

